services:
  server:
    build: server/
    command: python ./server.py
    ports:
      - "1234:1234"
    environment:
      - DEBUG=false
  client:
    build: client/
    command: python ./client.py
    network_mode: host
    depends_on:
      - server
    environment:
      - DEBUG=false
    restart: on-failure


